bookings/urls.py
from django.conf.urls import url
from django.contrib import admin

from hotels import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hotels$', views.index),
]

hotels/models.py
from __future__ import unicode_literals

from django.db import models

'''Classe de gestion des hotels'''


class Hotel(models.Model):
    nom = models.CharField(max_length=255)
    description = models.TextField()
    etoiles = models.PositiveSmallIntegerField()
    chambres = models.PositiveIntegerField()
    photo = models.ImageField(null=True)
    # prix = models.DecimalField()
    contact = models.EmailField()
    note = models.DecimalField(decimal_places=1, max_digits=5, null=True)
    date_creation = models.DateField(null=True)
    actif = models.BooleanField(default=True)

    def __str__(self):
        return self.nom

    '''Classe de gestion des chambres'''
    '''Hotel peut avoir plusieurs chambres'''

class Chambre(models.Model):
    numero = models.CharField(max_length=5)
    disponible = models.BooleanField()
    hotel = models.ForeignKey(Hotel)

hotels/views.py
from django.shortcuts import render
from models import Hotel


# crer une methode
def index(request):
    #hotels = Hotel.objects.filter( etoiles__gt=2, description__contains='nice').order_by('nom')
    hotels = Hotel.objects.all()
    data = {
        'hotels': hotels,
        'title': 'Liste des hotels',
    }
    return render(request, 'index.html', data)

# Create your views here.

hotels/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<h1>{{ title }}</h1>

<ul>
    {% for hot in hotels %}
    <li>{{ hot.nom }}</li>
        <ul>
        {% for cha in hotel.chambre_set.all %}
            <li>{{ cha.numero }} : {{ cha.disponible }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
</ul>


</body>
</html>